### ISSUE TITLE
validate_* functions deprecated

### ISSUE THREAD

**Issue by jtreminio** [petems/petems-swap_file#80]
On Puppet 5.x+ get the following:

    Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Hash. There is further documentation for validate_legacy function in the README.

**Comment by petems** [comment]
Yeah I hadn't got round to updating this since I didn't want to break compatibility when Puppet 4 was new, but it's been long enough I should update and do a major version bump.

@jtreminio Can you open a PR to make the change you made in https://github.com/jtreminio/petems-swap_file/commit/a497b192d0cbeaab754448caffda51ffbe9fbbfb?

**Comment by KrzysztofHajdamowicz** [comment]
@jtreminio @petems bump

**Comment by petems** [comment]
Finally merged and tests are green now 👍

**Comment by alexpdp7** [comment]
Works for me!
